In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("./data/emails.csv") 
df.head()

,id,sender,subject,date,body
0,1a0eeb7af2e50e02,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation,"Tue, 29 Sep 2026 19:50:10 +0000 (UTC)",You have 1 new invitation\r\nView invitations:...
1,1a0eea33be2c606f,Codecademy <learn@itr.mail.codecademy.com>,6 AI skills worth learning this week,"Tue, 29 Sep 2026 19:27:49 +0000",A software engineer's take on managing AI inst...
2,1a0ee7f368c3a9d5,Google <no-reply@accounts.google.com>,Security alert,"Tue, 29 Sep 2026 18:48:28 GMT",[image: Google]\r\nYou allowed Gmail ML Classi...
3,1a0ee1b30aeb0787,LinkedIn <messages-noreply@linkedin.com>,Data Scientist: Harnham and Datatech Analytics...,"Tue, 29 Sep 2026 16:59:14 +0000 (UTC)",----------------------------------------\r\nHi...
4,1a0ee09e68b497a7,Standard Life <Emails@service.standardlife.co.uk>,Six ways to make more of your pension in 2026,"Tue, 29 Sep 2026 09:52:46 -0600","To view this email as a web page, go to the li..."

In [24]:
# shape
df.shape[0]

500

In [25]:
df.isna().sum()

id          0
sender      0
subject     2
date        0
body       89
dtype: int64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       500 non-null    object
 1   sender   500 non-null    object
 2   subject  498 non-null    object
 3   date     500 non-null    object
 4   body     411 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

In [27]:
# missing bodies
df[df["body"].isna()][["sender", "subject", "body"]]

,sender,subject,body
5,no-reply@employmenthero.com,Your timesheets have been updated,NaN
11,Anthropic Education <academy-support@anthropic...,Complete your signup,NaN
15,Uber <uber@uber.com>,Take the work out of going to work,NaN
17,Revolut <no-reply@revolut.com>,You sent £7.99 to Clement Appeadu 💸,NaN
18,no-reply@employmenthero.com,Your timesheets have been updated,NaN
...,...,...,...
488,Uber <uber@uber.com>,Stay prepared with your trips and get 20% off,NaN
489,Kwame from Bolt <ghana@rides-marketing.bolt.eu>,Get more than just a ride 🍔,NaN
490,Uber Receipts <noreply@uber.com>,[Personal] Your Monday morning trip with Uber,NaN
493,Uber <uber@uber.com>,"Clement, Grab £5 off your first in-app train t...",NaN
495,Uber Receipts <noreply@uber.com>,[Personal] Your Sunday morning trip with Uber,NaN

In [28]:
# visual inspection reveals that these are empty because the body contains images which have the message 
# of the email.

In [29]:
# no subject
df[df["subject"].isna()][["sender", "subject", "body"]]

,sender,subject,body
85,CLEMENT APPEADU <appeaduclement@gmail.com>,NaN,# RiskLens foundation and modeling plan\r\n\r\...
162,Clement Appeadu <clementappeaduspiky@gmail.com>,NaN,Fya\r\n\r\n

In [30]:
# for this is subject was actually not given

In [31]:
# understand senders
df["sender"].value_counts().head(20)

sender
LinkedIn Job Alerts <jobalerts-noreply@linkedin.com>                  62
LinkedIn <notifications-noreply@linkedin.com>                         46
LinkedIn <messages-noreply@linkedin.com>                              37
no-reply@employmenthero.com                                           28
Debenhams Outlet <news@email.debenhamsoutlet.com>                     27
Uber <uber@uber.com>                                                  21
LinkedIn <updates-noreply@linkedin.com>                               19
LinkedIn <jobs-noreply@linkedin.com>                                  19
Codecademy <learn@itr.mail.codecademy.com>                            18
Skyscanner <no-reply@sender.skyscanner.com>                           18
National Express <nx-reply@nationalexpress.com>                       16
Stream <hello@comms.stream.co>                                        13
Google <no-reply@accounts.google.com>                                 11
Uber Receipts <noreply@uber.com>                                      10
Virgin Red <noreply@rewards.red.virgin.com>                            7
Lloyds Bank <info@emails.lloydsbank.com>                               7
OmniBSIC Bank <campaigns@omnibsic.com.gh>                              7
Dan at Real Python <info@realpython.com>                               6
OpenAI <noreply@tm.openai.com>                                         6
Virgin Atlantic Flying Club <flyingclub@emails.virginatlantic.com>     6
Name: count, dtype: int64

In [32]:
# understand subjects
df["subject"].head(20)

0                             You have 1 new invitation
1                  6 AI skills worth learning this week
2                                        Security alert
3     Data Scientist: Harnham and Datatech Analytics...
4         Six ways to make more of your pension in 2026
5                     Your timesheets have been updated
6     Check out your latest offers from Stream Rewar...
7     🚨 Clement, Outlet                             ...
8                          Why wait to invest, Clement?
9         Senior Human Resources Officer at Talent Ogin
10    Your registration for Building with the Claude...
11                                 Complete your signup
12    Emmanuela Amadi - Project Manager reacted to t...
13                            You have 1 new invitation
14       With fares from £7.50*, get away this autumn 🍂
15                   Take the work out of going to work
16                SALE EXTENDED: Back to school 50% off
17                  You sent £7.99 to Clement Appeadu 💸
18                    Your timesheets have been updated
19                         Data Scientist at Data Idols
Name: subject, dtype: object

In [33]:
# mini report

print("Shape:", df.shape)

print("\nMissing values:")
print(df.isna().sum())

print("\nTop senders:")
print(df["sender"].value_counts().head(20))

print("\nFirst 50 emails:")
display(df[["sender", "subject"]].head(50))

Shape: (500, 5)

Missing values:
id          0
sender      0
subject     2
date        0
body       89
dtype: int64

Top senders:
sender
LinkedIn Job Alerts <jobalerts-noreply@linkedin.com>                  62
LinkedIn <notifications-noreply@linkedin.com>                         46
LinkedIn <messages-noreply@linkedin.com>                              37
no-reply@employmenthero.com                                           28
Debenhams Outlet <news@email.debenhamsoutlet.com>                     27
Uber <uber@uber.com>                                                  21
LinkedIn <updates-noreply@linkedin.com>                               19
LinkedIn <jobs-noreply@linkedin.com>                                  19
Codecademy <learn@itr.mail.codecademy.com>                            18
Skyscanner <no-reply@sender.skyscanner.com>                           18
National Express <nx-reply@nationalexpress.com>                       16
Stream <hello@comms.stream.co>                                        13
Google <no-reply@accounts.google.com>                                 11
Uber Receipts <noreply@uber.com>                                      10
Virgin Red <noreply@rewards.red.virgin.com>                            7
Lloyds Bank <info@emails.lloydsbank.com>                               7
OmniBSIC Bank <campaigns@omnibsic.com.gh>                              7
Dan at Real Python <info@realpython.com>                               6
OpenAI <noreply@tm.openai.com>                                         6
Virgin Atlantic Flying Club <flyingclub@emails.virginatlantic.com>     6
Name: count, dtype: int64

First 50 emails:

,sender,subject
0,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation
1,Codecademy <learn@itr.mail.codecademy.com>,6 AI skills worth learning this week
2,Google <no-reply@accounts.google.com>,Security alert
3,LinkedIn <messages-noreply@linkedin.com>,Data Scientist: Harnham and Datatech Analytics...
4,Standard Life <Emails@service.standardlife.co.uk>,Six ways to make more of your pension in 2026
5,no-reply@employmenthero.com,Your timesheets have been updated
6,Stream <hello@comms.stream.co>,Check out your latest offers from Stream Rewar...
7,Debenhams Outlet <news@email.debenhamsoutlet.com>,"🚨 Clement, Outlet ..."
8,Lloyds Bank Investing <info@emails.lloydsbank....,"Why wait to invest, Clement?"
9,LinkedIn Job Alerts <jobalerts-noreply@linkedi...,Senior Human Resources Officer at Talent Ogin
10,Anthropic Education <academy-support@anthropic...,Your registration for Building with the Claude...
11,Anthropic Education <academy-support@anthropic...,Complete your signup
12,LinkedIn <updates-noreply@linkedin.com>,Emmanuela Amadi - Project Manager reacted to t...
13,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation
14,National Express <nx-reply@nationalexpress.com>,"With fares from £7.50*, get away this autumn 🍂"
15,Uber <uber@uber.com>,Take the work out of going to work
16,Codecademy <learn@itr.mail.codecademy.com>,SALE EXTENDED: Back to school 50% off
17,Revolut <no-reply@revolut.com>,You sent £7.99 to Clement Appeadu 💸
18,no-reply@employmenthero.com,Your timesheets have been updated
19,LinkedIn <jobs-noreply@linkedin.com>,Data Scientist at Data Idols
20,National Express <nx-reply@nationalexpress.com>,🎁10% off is waiting for you...
21,Debenhams Outlet <news@email.debenhamsoutlet.com>,"💸 Clement, New In: At Least 60% Off ..."
22,Virgin Red <noreply@rewards.red.virgin.com>,Get up to 70% bonus Virgin Points when you buy...
23,Greggs <hello@emails.greggs.co.uk>,Win a thrilling trip to Alton Towers Resort 👻🎢
24,LinkedIn Job Alerts <jobalerts-noreply@linkedi...,"Project Administrator at Niyukti Systems, Inc"
25,Octopus Energy <hello@octopus.energy>,FYI: We'll take a £57.93 payment on 5th Octobe...
26,Uber <uber@uber.com>,Stay prepared with your trips and get 20% off
27,Google <no-reply@accounts.google.com>,Someone added you as their recovery email
28,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation
29,Stream <hello@comms.stream.co>,New to Phlo Clinic? Save up to £50 on your fir...
30,Uber <uber@uber.com>,Get £5 off your first train ticket today
31,LinkedIn <notifications-noreply@linkedin.com>,You appeared in 4 searches
32,LinkedIn Job Alerts <jobalerts-noreply@linkedi...,HWF (Wh&L) Docs Specialist/Data Entry) (MJ0024...
33,LinkedIn <messages-noreply@linkedin.com>,3 people viewed your profile
34,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation
35,"""Boots Bot from Boot.dev"" <boots@system.boot.dev>",Boot.dev Email Verification
36,Codecademy <learn@itr.mail.codecademy.com>,50% off ends soon
37,LinkedIn Job Alerts <jobalerts-noreply@linkedi...,Senior HR Coordinator - Expression of Interest...
38,LinkedIn <updates-noreply@linkedin.com>,Sedem Thomas Quashie - Relationship Officer re...
39,OmniBSIC Bank <campaigns@omnibsic.com.gh>,KNUST Fees Due? Pay with Ease at OmniBSIC Bank
40,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation
41,National Express <nx-reply@nationalexpress.com>,Airport transfers from £11.40 ✈️
42,LinkedIn <messages-noreply@linkedin.com>,Data Scientist: Faculty hired near you
43,Virgin Atlantic Flying Club <flyingclub@emails...,Save up to £300 on holidays
44,Dan at Real Python <info@realpython.com>,Your Real Python Mentor
45,LinkedIn Job Alerts <jobalerts-noreply@linkedi...,"School Officer at Department of Education, Wes..."
46,donotreply@notify.sage.com,Verify it's you - 362756
47,noreply@sagepayrollservices.co.uk,New Online Payslip
48,OpenAI <noreply@email.openai.com>,Steer your agent without starting over
49,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation

In [34]:
df_annotated = pd.read_csv("./data/annotated_emails.csv") 
df_annotated.head()

,id,sender,subject,date,body,label
0,1a0eeb7af2e50e02,LinkedIn <notifications-noreply@linkedin.com>,You have 1 new invitation,"Tue, 29 Sep 2026 19:50:10 +0000 (UTC)",You have 1 new invitation\r\nView invitations:...,notifications
1,1a0eea33be2c606f,Codecademy <learn@itr.mail.codecademy.com>,6 AI skills worth learning this week,"Tue, 29 Sep 2026 19:27:49 +0000",A software engineer's take on managing AI inst...,education
2,1a0ee7f368c3a9d5,Google <no-reply@accounts.google.com>,Security alert,"Tue, 29 Sep 2026 18:48:28 GMT",[image: Google]\r\nYou allowed Gmail ML Classi...,notifications
3,1a0ee1b30aeb0787,LinkedIn <messages-noreply@linkedin.com>,Data Scientist: Harnham and Datatech Analytics...,"Tue, 29 Sep 2026 16:59:14 +0000 (UTC)",----------------------------------------\r\nHi...,jobs
4,1a0ee09e68b497a7,Standard Life <Emails@service.standardlife.co.uk>,Six ways to make more of your pension in 2026,"Tue, 29 Sep 2026 09:52:46 -0600","To view this email as a web page, go to the li...",finance

In [35]:
df_annotated['label'].value_counts()

label
notifications     137
jobs               98
social_media       64
transportation     64
finance            40
work               36
education          29
personal           24
shopping            8
Name: count, dtype: int64

In [36]:
print(df_annotated.shape)

print("\nLabel counts:")
print(df_annotated["label"].value_counts())

print("\nMissing labels:")
print(df_annotated["label"].isna().sum())

print("\nDuplicate email IDs:")
print(df_annotated["id"].duplicated().sum())

(500, 6)

Label counts:
label
notifications     137
jobs               98
social_media       64
transportation     64
finance            40
work               36
education          29
personal           24
shopping            8
Name: count, dtype: int64

Missing labels:
0

Duplicate email IDs:
0

In [37]:
df_annotated["label"].value_counts(normalize=True).mul(100).round(2)

label
notifications     27.4
jobs              19.6
social_media      12.8
transportation    12.8
finance            8.0
work               7.2
education          5.8
personal           4.8
shopping           1.6
Name: proportion, dtype: float64

In [ ]:
# try preprocessing from src
from src.preprocessing import clean_text

df_annotated_v1 = df_annotated.copy()

df_annotated_v1["text"] = (
    df["subject"].fillna("")
    + " "
    + df["body"].fillna("")
)

df["clean_text"] = df["text"].apply(clean_text)